/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThriveSpaceRouteImport } from './routes/thrive-space'
import { Route as ScalingRouteImport } from './routes/scaling'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConflictRouteImport } from './routes/conflict'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdvisingRouteImport } from './routes/advising'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const ThriveSpaceRoute = ThriveSpaceRouteImport.update({
  id: '/thrive-space',
  path: '/thrive-space',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalingRoute = ScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictRoute = ConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisingRoute = AdvisingRouteImport.update({
  id: '/advising',
  path: '/advising',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advising': typeof AdvisingRoute
  '/archive': typeof ArchiveRoute
  '/books': typeof BooksRoute
  '/conflict': typeof ConflictRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/scaling': typeof ScalingRoute
  '/thrive-space': typeof ThriveSpaceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advising': typeof AdvisingRoute
  '/archive': typeof ArchiveRoute
  '/books': typeof BooksRoute
  '/conflict': typeof ConflictRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/scaling': typeof ScalingRoute
  '/thrive-space': typeof ThriveSpaceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advising': typeof AdvisingRoute
  '/archive': typeof ArchiveRoute
  '/books': typeof BooksRoute
  '/conflict': typeof ConflictRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/scaling': typeof ScalingRoute
  '/thrive-space': typeof ThriveSpaceRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advising'
    | '/archive'
    | '/books'
    | '/conflict'
    | '/contact'
    | '/leadership'
    | '/scaling'
    | '/thrive-space'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advising'
    | '/archive'
    | '/books'
    | '/conflict'
    | '/contact'
    | '/leadership'
    | '/scaling'
    | '/thrive-space'
    | '/insights/$slug'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advising'
    | '/archive'
    | '/books'
    | '/conflict'
    | '/contact'
    | '/leadership'
    | '/scaling'
    | '/thrive-space'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisingRoute: typeof AdvisingRoute
  ArchiveRoute: typeof ArchiveRoute
  BooksRoute: typeof BooksRoute
  ConflictRoute: typeof ConflictRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  ScalingRoute: typeof ScalingRoute
  ThriveSpaceRoute: typeof ThriveSpaceRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thrive-space': {
      id: '/thrive-space'
      path: '/thrive-space'
      fullPath: '/thrive-space'
      preLoaderRoute: typeof ThriveSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scaling': {
      id: '/scaling'
      path: '/scaling'
      fullPath: '/scaling'
      preLoaderRoute: typeof ScalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict': {
      id: '/conflict'
      path: '/conflict'
      fullPath: '/conflict'
      preLoaderRoute: typeof ConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advising': {
      id: '/advising'
      path: '/advising'
      fullPath: '/advising'
      preLoaderRoute: typeof AdvisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisingRoute: AdvisingRoute,
  ArchiveRoute: ArchiveRoute,
  BooksRoute: BooksRoute,
  ConflictRoute: ConflictRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute: LeadershipRoute,
  ScalingRoute: ScalingRoute,
  ThriveSpaceRoute: ThriveSpaceRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
